# Generated by Django 2.2.8 on 2020-01-20 12:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpage',
            name='related_document',
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document_page_description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document_page_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='DocumentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='document.DocumentPage')),
                ('related_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
