# Generated by Django 2.2.8 on 2019-12-12 15:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('nickname', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('position', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('age', wagtail.core.blocks.CharBlock(max_length=2, required=False)), ('height', wagtail.core.blocks.CharBlock(max_length=10, required=False)), ('occupation', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('playing_style', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
