# Generated by Django 2.2.8 on 2019-12-12 15:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('nickname', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('position', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('age', wagtail.core.blocks.CharBlock(max_length=2, required=False)), ('height', wagtail.core.blocks.CharBlock(max_length=10, required=False)), ('occupation', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('playing_style', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Player Stats Page',
                'verbose_name_plural': 'Player Stats Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
