# Generated by Django 2.2.8 on 2019-12-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerpage',
            options={},
        ),
    ]
