# Generated by Django 2.2.8 on 2019-12-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20191212_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='playerpage',
            name='subtitle',
        ),
    ]
