# Generated by Django 2.2.8 on 2019-12-12 16:06

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20191212_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('nickname', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('position', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('age', wagtail.core.blocks.CharBlock(max_length=2, required=False)), ('height', wagtail.core.blocks.CharBlock(max_length=10, required=False)), ('occupation', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('playing_style', wagtail.core.blocks.CharBlock(max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
