# Generated by Django 2.2.8 on 2019-12-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_playerpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpage',
            name='content',
        ),
    ]
