# Generated by Django 2.2.8 on 2019-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20191216_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetailpage',
            name='age',
            field=models.CharField(blank=True, help_text='Player Age', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='playerdetailpage',
            name='height',
            field=models.CharField(blank=True, help_text='Player Height', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playerdetailpage',
            name='occupation',
            field=models.CharField(blank=True, help_text='Player Occupation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playerdetailpage',
            name='playing_style',
            field=models.CharField(blank=True, help_text='Player playing style', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playerdetailpage',
            name='position',
            field=models.CharField(default='Attack', help_text='Player Position', max_length=40),
            preserve_default=False,
        ),
    ]
