# Generated by Django 2.2.8 on 2020-01-23 09:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_content',
            field=wagtail.core.fields.StreamField([('news_items', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.TextBlock(max_length=100, required=True)), ('story', wagtail.core.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True),
        ),
    ]
