# Generated by Django 2.2.8 on 2019-12-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='flex_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
